### ISSUE TITLE
I didn't know where to post this...

### ISSUE THREAD

**Issue by algonorth** [scryfall/api-types#28]
I love what you're doing and I've been working on a Magic the Gathering web app based off of Scryfall data. I'd like to keep my UUIDs the same as Scryfalls. I'm assuming they're generated in a deterministic manner. Could you tell me what combination you're using (set, lang, card name, etc.) so I can have the same UUIDs for my database as well? 

I love what you're doing! :)

**Comment by scarletcs** [comment]
This is the issues form for a prerelease project just describing the API in typescript, not a good place for API questions themselves. We have [a feedback form](https://scryfall.com/admin/feedback) where you can ask us questions and if you leave a reply email we can reply to you. Additionally, if you have a Scryfall account, you can become a Scryfall supporter and gain access to our discord where we have an API help channel. (If you're already a supporter but don't have your Discord invite, send us a message via the feedback form.)

That said, Scryfall UUIDs aren't deterministic. In fact making them deterministic would defeat the point for us. The distinct advantage of a UUIDv4 is that in even a large dataset we can be virtually guaranteed we will never generate the same UUID twice ever in the entire project's lifetime.

We suggest you generate your own IDs yourself and keep a `scryfall_id` column.
