### ISSUE TITLE
Layout "battle" cards are returned as layout "transform"

### ISSUE THREAD

**Issue by JoschiZ** [scryfall/api-types#31]
Hey there,

I hope this is the correct repository, if not I would be happy to file it at the correct place if you direct me there.

The docs and the type script typing in this repo state that battle cards have a value of `layout: "battle"` but they are actually listed as `layout: transform`.
That is why the search `layout:battle` https://scryfall.com/search?as=grid&extras=true&lang=any&order=name&q=layout%3Abattle&unique=cards returns no cards.

See https://api.scryfall.com/cards/318c363b-61cc-4e2f-8f86-a4287539ea07?format=json&pretty=true as an example of a battle card.

**Comment by scarletcs** [comment]
This library is just for describing the API's types, not for the API itself. You can report API issues via [the contact form](https://scryfall.com/contact).

That said, we added the `battle` layout when we saw battle cards, _then_ found out they transformed. So right now they are just `transform`.

It's on our radar to consider whether a better layout is appropriate.

**Comment by JoschiZ** [comment]
Thanks for the quick answer and linking the contact form.
