### ISSUE TITLE
Release new NPM package version

### ISSUE THREAD

**Issue by thesilican** [scryfall/api-types#6]
I'm using the latest version of this package from npm (`1.0.0-alpha.2`), I'm experiencing the same import issue as fixed by #2, so it seems like that PR isn't in the latest npm version.

![image](https://github.com/scryfall/api-types/assets/26753734/d2f7fc01-dbc4-4c5f-b328-bd770fc78c3f)

**Comment by billdami** [comment]
@thesilican fyi, until this is released, you can just point your dependency to the github tag to resolve these TS errors:
```
"@scryfall/api-types": "scryfall/api-types#v1.0.0-alpha.3",
```

**Comment by scarletcs** [comment]
I'll release these alpha versions shortly. We're in prerelease right now and I got held up for #10, but I'll endeavour to keep this library up to date regardless of being in prerelease — and I just recently figured out how to solve that particular issue.

**Comment by scarletcs** [comment]
v1.0.0-alpha.4 is now out.

I'm skipping v1.0.0-alpha.3 because it didn't have a correct version set for package.json. We'll get an automatic release process set up here by the time v1.0.0 proper is released.
